name: Android CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decode and Save Keystore
        run: |
          echo "${{ secrets.SIGNING_STORE_FILE }}" | base64 -d > app/keystore.jks

      - name: Extract Version Name
        id: get_version
        run: echo "VERSION_NAME=$(./gradlew -q printVersionName)" >> $GITHUB_ENV
        env:
          SIGNING_STORE_FILE: keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Build APK
        run: ./gradlew :app:assembleDebug :app:assembleRelease
        env:
          SIGNING_STORE_FILE: keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Upload Debug APK (for main branch pushes)
        if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')
        uses: actions/upload-artifact@v3
        with:
          name: Tokification-debug-${{ env.VERSION_NAME }}
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Rename Release APK
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/Tokification-${{ env.VERSION_NAME }}.apk

      - name: Create Release (for tagged pushes)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/Tokification-${{ env.VERSION_NAME }}.apk
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
