name: Android Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [ 35 ]
        target: [ android-35 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}

      - name: Decode and Save Keystore
        run: |
          echo "${{ secrets.SIGNING_STORE_FILE }}" | base64 -d > app/keystore.jks

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release Version
        run: ./gradlew assembleRelease --no-daemon
        env:
          SIGNING_STORE_FILE: keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Extract Version Name
        id: get_version
        run: echo "VERSION_NAME=$(./gradlew -q printVersionName)" >> $GITHUB_ENV
        env:
          SIGNING_STORE_FILE: keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Rename and Upload Release APK to Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Tokification-${{ env.VERSION_NAME }}
          path: app/build/outputs/apk/release/app-release.apk

      - name: Create Proguard mapping file artifact
        uses: actions/upload-artifact@v3
        with:
          name: proguard-mapping
          path: app/build/outputs/mapping/release/mapping.txt

      - name: Upload APK to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: Tokification-${{ env.VERSION_NAME }}
          asset_content_type: application/vnd.android.package-archive
